# Generated by Django 5.0.6 on 2024-07-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('rating', models.IntegerField(default=0)),
                ('genres', models.JSONField()),
                ('in_theaters', models.BooleanField(default=False)),
            ],
        ),
    ]
